# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: quicksort-go-aws-lambda-build
run-name: quicksort-go-aws-lambda-build run by ${{ github.actor }}
on:
  workflow_dispatch:
env:
  AWS_REGION: "ap-southeast-2"
  S3_BUCKET_NAME : "quicksort-go-lambda-bucket"
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOOS: linux
      GOARCH: arm64
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.3'

    - name: Test
      run: go test -v ./...

    - name: Build
      run: go build -tags lambda.norpc -o bootstrap -v ./...

    - name: Create zip file
      run: |
        zip bootstrap.zip bootstrap

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::508298911387:role/GitHubAction-AssumeRoleWithAction
        aws-region: ${{ env.AWS_REGION }}

    - name: Push zip to S3 bucket
      run: |
        aws s3 cp ./bootstrap.zip s3://${{ env.S3_BUCKET_NAME }}/
